spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Swagger / OpenAPI (springdoc)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/BlueprintDB
spring.datasource.username=jacobo
spring.datasource.password=jacobo123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

